### ISSUE TITLE
NullPointerException when parsing Capabilities without Title

### ISSUE THREAD

**Issue by ridoo** [52North/OX-Framework#28]
I got an other problem with my
SWC 3.2.0 when I execute the application on my tomcat's server:

java.lang.IndexOutOfBoundsException: null

This is the fist time i got that in my log. I verify for be sure to have the
good version of oxf adaptater.
I configure my client with 1.0.0 sos version and I use sos v 3.6.0.
I attach the complete error after.

**My log:**

```
2014-06-07 12:29:08,319 WARN [http-bio-8080-exec-9] [ConnectorUtils.java:83]
Error executing capabilities request,  SOS URL:
'http://localhost:8080/SOS2/sos', SOSAdapter:
org.n52.server.da.oxf.SOSAdapter_OXFExtension
java.lang.IndexOutOfBoundsException: null
        at
net.opengis.ows.x11.impl.DescriptionTypeImpl.getTitleArray(DescriptionTypeImpl.java:59)
~[52n-xml-ows-v110-1.1.5.jar:1.1.5]
        at
org.n52.oxf.sos.adapter.SOSCapabilitiesMapper_100.mapServiceIdentification(SOSCapabilitiesMapper_100.java:512)
~[oxf-sos-adapter-2.0.0-alpha.3.jar:2.0.0-alpha.3]
        at
org.n52.oxf.sos.adapter.SOSCapabilitiesMapper_100.mapCapabilities(SOSCapabilitiesMapper_100.java:93)
~[oxf-sos-adapter-2.0.0-alpha.3.jar:2.0.0-alpha.3]
        at
org.n52.oxf.sos.adapter.SOSAdapter.initService(SOSAdapter.java:231)
~[oxf-sos-adapter-2.0.0-alpha.3.jar:2.0.0-alpha.3]
        at
org.n52.oxf.sos.adapter.SOSAdapter.initService(SOSAdapter.java:197)
~[oxf-sos-adapter-2.0.0-alpha.3.jar:2.0.0-alpha.3]
        at
org.n52.server.da.oxf.SOSAdapter_OXFExtension.initService(SOSAdapter_OXFExtension.java:74)
~[sensorwebclient-api-3.2.0.jar:na]
        at
org.n52.server.sos.parser.ConnectorUtils$1.call(ConnectorUtils.java:68)
~[sensorwebclient-api-3.2.0.jar:na]
        at
org.n52.server.sos.parser.ConnectorUtils$1.call(ConnectorUtils.java:65)
~[sensorwebclient-api-3.2.0.jar:na]
        at
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
~[na:1.6.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
~[na:1.6.0_31]
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
~[na:1.6.0_31]
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
~[na:1.6.0_31] at java.lang.Thread.run(Thread.java:701) ~[na:1.6.0_31] 
```

**Comment by EHJ-52n** [comment]
Closed because project is archived.
