### ISSUE TITLE
NullPointerException in SOSCapabilitiesMapper_100.mapContents()

### ISSUE THREAD

**Issue by johnjohndoe** [52North/OX-Framework#37]
I compiled the [sos-importer](https://github.com/52North/sos-importer) from source ([b5548](https://github.com/52North/sos-importer/commit/b554826d94f6ccdd48deea26e528da3b8c66214a)). Here is the console output:

```
java -jar 52n-sos-importer-feeder-0.4.0-SNAPSHOT-bin.jar -c data.csv.52n-sos-import-config.xml 

12:04:09.896 [main] INFO  Feeder - Application started
		Created-By: 1.7.0_65 (Oracle Corporation)
		Manifest-Version: 1.0
		Main-Class: jdk.nashorn.tools.Shell
		HeapSize Information: max: 850MB; total now: 57MB; free now: 42MB; used now: 14MB
		os.name: Linux; os.arch: amd64; os.version: 3.16.0-31-generic
12:04:10.341 [OneTimeFeeder] INFO  OneTimeFeeder - Starting feeding data from file via 
    configuration 'data.csv.52n-sos-import-config.xml' to SOS instance
12:04:10.363 [OneTimeFeeder] TRACE SensorObservationService - 
    SensorObservationService(Configuration [file=data.csv.52n-sos-import-config.xml])
12:04:10.556 [OneTimeFeeder] DEBUG SimpleHttpClient - executing POST method 
    to 'http://localhost:8080/52n-sos-webapp/sos'.

Exception in thread "OneTimeFeeder" java.lang.NullPointerException
	at org.n52.oxf.sos.adapter.v100.SOSCapabilitiesMapper_100.mapContents(SOSCapabilitiesMapper_100.java:273)
	at org.n52.oxf.sos.adapter.v100.SOSCapabilitiesMapper_100.mapCapabilities(SOSCapabilitiesMapper_100.java:98)
	at org.n52.oxf.sos.adapter.SOSAdapter.initService(SOSAdapter.java:273)
	at org.n52.oxf.sos.adapter.SOSAdapter.initService(SOSAdapter.java:239)
	at org.n52.oxf.sos.adapter.SOSAdapter.initService(SOSAdapter.java:232)
	at org.n52.oxf.sos.adapter.wrapper.SosWrapperFactory.doGetCapabilities(SosWrapperFactory.java:84)
	at org.n52.oxf.sos.adapter.wrapper.SosWrapperFactory.newInstance(SosWrapperFactory.java:65)
	at org.n52.sos.importer.feeder.SensorObservationService.<init>(SensorObservationService.java:189)
	at org.n52.sos.importer.feeder.task.OneTimeFeeder.run(OneTimeFeeder.java:162)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by EHJ-52n** [comment]
@johnjohndoe 

Do you have any data in the SOS instance?
Do you see any offering when requesting the GetCapabilities limiting to the contents section?

**Comment by johnjohndoe** [comment]
The instance is blank. I tried to import new data.

**Comment by johnjohndoe** [comment]
I also tried the [example tutorial](https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Example_tutorial) with the [demo data](https://wiki.52north.org/bin/view/SensorWeb/SosImporter#Demo_data). Same error, though.

**Comment by ridoo** [comment]
@EHJ-52n are you willing to have a look at this?

**Comment by EHJ-52n** [comment]
@johnjohndoe you might think about switching to SOS 2.0.0 specification.
